"""Add advanced billing and time tracking models

Revision ID: 146ba6198f22
Revises: c4da9f5c5d4c
Create Date: 2025-08-05 16:37:22.951565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146ba6198f22'
down_revision = 'c4da9f5c5d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hours_worked', sa.Float(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('hourly_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('flat_fee_amount', sa.Float(), nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('override_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('task_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_billable', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('has_been_billed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('has_been_billed')
        batch_op.drop_column('is_billable')
        batch_op.drop_column('quantity')
        batch_op.drop_column('task_fee')
        batch_op.drop_column('override_rate')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('flat_fee_amount')
        batch_op.drop_column('hourly_rate')
        batch_op.drop_column('billing_type')

    op.drop_table('time_entry')
    # ### end Alembic commands ###
