"""Link tasks to line items and add invoice sequence

Revision ID: 1d47de7d7d1c
Revises: 146ba6198f22
Create Date: 2025-08-05 18:34:29.843754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d47de7d7d1c'
down_revision = '146ba6198f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('next_invoice_num', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_task_line_item_id', 'line_item', ['line_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_line_item_id', type_='foreignkey')
        batch_op.drop_column('line_item_id')

    op.drop_table('invoice_sequence')
    # ### end Alembic commands ###
