"""Add Client model and link to Project

Revision ID: 41555f8b2ac6
Revises: 18306326b89c
Create Date: 2025-08-04 00:16:06.360108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41555f8b2ac6'
down_revision = '18306326b89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_project_client_id", 'client', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint("fk_project_client_id", type_='foreignkey')
        batch_op.drop_column('client_id')

    op.drop_table('client')
    # ### end Alembic commands ###
