"""Add billing_type and fixed_rate to Project

Revision ID: 8fc0c49edb5a
Revises: 9f131fc2315b
Create Date: 2025-08-03 09:17:28.845754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc0c49edb5a'
down_revision = '9f131fc2315b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_type', sa.String(length=20), nullable=False, server_default='hourly')) # <-- FIX IS HERE
        batch_op.add_column(sa.Column('fixed_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('fixed_rate')
        batch_op.drop_column('billing_type')

    # ### end Alembic commands ###
