"""Add Task model

Revision ID: 965c569b812f
Revises: 41555f8b2ac6
Create Date: 2025-08-04 01:13:54.060429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965c569b812f'
down_revision = '41555f8b2ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
