"""Add deadline to Project model

Revision ID: 9f131fc2315b
Revises: c326ffbb82cb
Create Date: 2025-08-03 08:45:33.156718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f131fc2315b'
down_revision = 'c326ffbb82cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###
