"""Add notes field to Project model

Revision ID: a02036b5c88c
Revises: dd11ee8615c0
Create Date: 2025-08-04 06:58:57.027783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a02036b5c88c'
down_revision = 'dd11ee8615c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
