"""Add quantity_is_na flag to Task

Revision ID: a2b0015cf6d4
Revises: 1d47de7d7d1c
Create Date: 2025-08-05 20:08:05.563700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b0015cf6d4'
down_revision = '1d47de7d7d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_is_na', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('quantity_is_na')

    # ### end Alembic commands ###
