"""Add email column to User model

Revision ID: c4da9f5c5d4c
Revises: a02036b5c88c
Create Date: 2025-08-04 18:51:40.050822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4da9f5c5d4c'
down_revision = 'a02036b5c88c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False))
        batch_op.create_unique_constraint("uq_user_email", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_email", type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
